Repository iiCe89/Lynk_Social, pull requests merged in 2019-10, with the labels that each got.

#8 Done Issue #5
  app/Http/Controllers/ProfileController.php
  app/Http/Requests/ProfileUpdateRequest.php
  app/User.php
  config/filesystems.php
  database/migrations/2014_10_12_000000_create_users_table.php
  readme.md
  resources/views/auth/login.blade.php
  resources/views/includes/_navigation.blade.php
  resources/views/profile.blade.php
  resources/views/profile/index.blade.php
  routes/web.php
Labels: HacktoberFest, Pending-PR

#17 Code of conduct document
  docs/CODE_OF_CONDUCT.md
Labels: HacktoberFest

#25 Fixed issue where user is deleted when updating profile
  app/Http/Controllers/ProfileController.php
  composer.json
  composer.lock
  config/clockwork.php
  resources/views/profile.blade.php
  storage/clockwork/.gitignore
Labels: bug-found

#26 Avatar Uploads Refactor
  app/Http/Controllers/ProfileController.php
  app/Managers/ImageManager.php
  app/User.php
  resources/views/profile.blade.php
Labels: bug-found
